### ISSUE TITLE
Dependency conflict, and a possible error in requirements.txt.

### ISSUE THREAD

**Issue by yashpote** [chenxi-yang/CAROL#1]
Hi,

I was trying to install all the required libraries with the command `pip install -r requirements.txt` and I ran into the error:

```
ERROR: Could not find a version that satisfies the requirement mbrl.egg==info (from versions: none)
ERROR: No matching distribution found for mbrl.egg==info
```

and on removal of that line, I ran into a series of dependency conflicts, starting with the requirement `torch==1.7.1` which gave me:
```
The conflict is caused by:
    The user requested torch==1.7.1
    auto-lirpa 0.3 depends on torch<1.13.0 and >=1.8.0
```

Relaxing  the requirement to `torch>=1.7.1` further leads to:

```
The conflict is caused by:
    The user requested omegaconf==2.1.0
    hydra-core 1.3.1 depends on omegaconf<2.4 and >=2.2
```

Then relaxing the above requirement to `omegaconf>=2.1.0` gives me a new conflict: 
```
The conflict is caused by:
    The user requested hydra-core>=1.3.1
    mbrl 0.1.5 depends on hydra-core==1.0.3
```

Finally requesting an older version of hydra-core, i.e. `hydra-core==1.0.3` solved all the conflicts.

I tried a fresh install on two systems and had the same issues, I'm using python3.8.12 via pyenv.

**Comment by chenxi-yang** [comment]
Hi Yash,

I fixed the issue by moving `hydra` and `auto-lirpa` out of the requirements.txt and updated the `README`. These two packages are not used during training but they are required for evaluation, of which the packages are covered by `requirements_proof.txt`. Please ignore the conflict warning when installing `hydra` and `auto-lirpa` for training.

Separately, the `omegaconf` package is updated and no longer supports the installation for 2.1.0 from `pip`. Thus, I updated the version to `2.2.0`. Please give it a try.
